### ISSUE TITLE
Error when using tap-notify with AVA

### ISSUE THREAD

**Issue by fernandofleury** [axross/tap-notify#3]
Whenever using tap-notify with [ava](https://github.com/sindresorhus/ava) I get this error:

``` javascript
// ava test/unit/*spec.js --tap | tap-notify

tap-notify/distributions/index.js:43
var passedOptions = Object.assign({}, DEFAULT_PASSED_OPTIONS, passed);

TypeError: undefined is not a function
    at createReporter (/Users/fernandofleury/n/lib/node_modules/tap-notify/distributions/index.js:43:30)
    at Object.<anonymous> (/Users/fernandofleury/n/lib/node_modules/tap-notify/distributions/cli.js:10:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

events.js:85
      throw er; // Unhandled 'error' event

Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:777:14)

npm ERR! Test failed.  See above for more details.
```

Others tap such as tap-nyan works just fine. Am I missing something here?

**Comment by jameswomack** [comment]
Same issue, but with tape itself. The issue is that older versions of Node do not have `Object.assign`.
